name: ci

on: [push, pull_request]

jobs:
  build-windows:

    runs-on: [ windows-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.2
        uses: foojayio/setup-java@disco
        with:
          java-version: 17.0.2
          architecture: x64
      - name: Build with Gradle
        run: .\gradlew.bat assemble
      - name: Create Distribution
        run: .\build_app_windows.bat
      - uses: actions/upload-artifact@v2
        with:
          name: GlucoStatusFX Windows
          path: '.\build\installer\GlucoStatusFX-17.0.9.msi'



  build-mac:

    runs-on: [ macos-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.2
        uses: foojayio/setup-java@disco
        with:
          java-version: 17.0.2
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Grant execute permission for build_app_macos.sh
        run: chmod +x ./build_app_macos.sh
      - name: Create Distribution
        run: ./build_app_macos.sh
      - uses: actions/upload-artifact@v2
        with:
          name: GlucoStatusFX Mac
          path: |
            ./build/installer/GlucoStatusFX-17.0.9.pkg
            ./build/installer/GlucoStatusFX-17.0.9.pkg.sha256
            ./build/libs/GlucoStatusFX-17.0.9.jar

  build-linux:

    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.2
        uses: foojayio/setup-java@disco
        with:
          java-version: 17.0.2
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Grant execute permission for build_app_linux.sh
        run: chmod +x ./build_app_linux.sh
      - name: Create Distribution
        run: ./build_app_linux.sh
      - uses: actions/upload-artifact@v2
        with:
          name: GlucoStatusFX Linux
          path: |
            ./build/installer/glucostatusfx_17.0.9-1_amd64.deb
            ./build/installer/glucostatusfx_17.0.9-1_amd64.deb.sha256
            ./build/installer/glucostatusfx-17.0.9-1_x86_64.rpm
            ./build/installer/glucostatusfx-17.0.9-1_x86_64.rpm.sha256
            ./build/libs/GlucoStatusFX-17.0.9.jar